My Application: NPC Class Reference
NPC Class Reference
This the NPC class.
#include <NPC.h>
Public Types
enum BodyParts {
HEAD, BODY, L_ARM, R_ARM,
L_LEG, R_LEG, NUM_BODYPARTS
}
Public Member Functions
NPC (void)
virtual ~NPC (void)
string getIdentity ()
virtual bool getCriteria ()
virtual void Init ()
Initializer.
virtual void Control (double dt, vector< Object * >object, Player *player)
virtual TextBox * getConversation (Player *player)
void InitDialogue (const char *filename)
Initialzier for the dialouge.
virtual void InitQuest (const char *filename)
Initialzier for hobo the quest text.
void Update (double dt, vector< Object * >object, Player *player)
Update function.
void Orientate (float o, double dt, float speed)
Orientation.
void Orientate (Vector3 t, double dt, float speed)
Overloaded orientation.
void Goto (Vector3 destination, double dt, float turn, float speed)
Go to function.
void Animate (double dt, float speed)
Animation.
void Animate (double dt, float speed, float limit)
Overloaded animate.
Public Member Functions inherited from dynamicObject
dynamicObject ()
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float o)
~dynamicObject ()
void UpdateVelocity (double dt)
bool Knockback (Vector3 dir, Vector3 vel)
void RespondToCollision (Vector3 initialPos, vector< Object * >object)
void RespondToCollision (Vector3 initialPos, vector< Object * >object, Player *player)
dynamicObj RespondToCollision
float getHealth ()
Public Member Functions inherited from Object
Object ()
Object (Vector3 p, Vector3 c, Vector3 h)
Basic constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i, bool paid)
virtual ~Object ()
virtual void Update (double dt)
virtual void setPaid (bool p)
virtual bool getPaid ()
virtual float getValue ()
virtual Vector3 getStorePos (Player *player)
Data Fields
Vector3 initialPos
Vector3 previousPos
Vector3 target
Bodypart bodyParts [NUM_BODYPARTS]
string identity
float rotation [NUM_BODYPARTS]
int rotationDir [NUM_BODYPARTS]
float elapsedTime
vector< TextBox > greetings
vector< TextBox > clues
Quest * quest
bool inConversation
Data Fields inherited from dynamicObject
Vector3 velocity
float hitDelay
float health
Data Fields inherited from Object
std::string type
Vector3 position
Collision collision
Mesh * mesh
float orientation
float size
bool ignoreCollision
Additional Inherited Members
Static Public Member Functions inherited from Object
static bool checkCollision (Object *a, Object *b)
Collsion checker function.
Detailed Description
This the NPC class.
Class NPC: dynamicObject
Definition at line 22 of file NPC.h.
Member Enumeration Documentation
enum NPC::BodyParts
Enumerator
HEAD
BODY
L_ARM
R_ARM
L_LEG
R_LEG
NUM_BODYPARTS
Definition at line 27 of file NPC.h.
Constructor & Destructor Documentation
NPC::NPC (void) inline
Definition at line 38 of file NPC.h.
References Collision::centre, Object::collision, elapsedTime, dynamicObject::health, Collision::hitbox, dynamicObject::hitDelay, Init(), Object::mesh, Object::orientation, Object::position, quest, Object::type, and Vector3::y.
virtual NPC::~NPC (void) inline virtual
Definition at line 54 of file NPC.h.
Member Function Documentation
void NPC::Animate (double dt, float speed)
Animation.
NPC:
Definition at line 110 of file NPC.cpp.
References L_ARM, NUM_BODYPARTS, rotation, rotationDir, dynamicObject::velocity, Vector3::x, and Vector3::z.
Referenced by Thug::Control(), Cashier::Control(), Blindman::Control(), Customer::Control(), S_Guard::Control(), and Update().
void NPC::Animate (double dt, float speed, float limit)
Overloaded animate.
NPC:
Definition at line 150 of file NPC.cpp.
References L_ARM, NUM_BODYPARTS, rotation, rotationDir, dynamicObject::velocity, Vector3::x, and Vector3::z.
virtual void NPC::Control (double dt, vector< Object * > object, Player * player) inline virtual
Reimplemented from dynamicObject.
Reimplemented in Manager, S_Guard, Detective, Customer, Blindman, Cashier, Thug, and Hobo.
Definition at line 72 of file NPC.h.
Referenced by Update().
virtual TextBox* NPC::getConversation (Player * player) inline virtual
Reimplemented in Detective, Cashier, and Hobo.
Definition at line 74 of file NPC.h.
References Quest::Accept, Button2D::altNext, Quest::criteria, Button2D::next, quest, and Button2D::trigger.
virtual bool NPC::getCriteria () inline virtual
Reimplemented in Manager.
Definition at line 69 of file NPC.h.
string NPC::getIdentity () inline virtual
Reimplemented from Object.
Definition at line 61 of file NPC.h.
Referenced by Detective::Control().
void NPC::Goto (Vector3 destination, double dt, float turn, float speed)
Go to function.
NPC:
Definition at line 222 of file NPC.cpp.
References Vector3::Dist(), elapsedTime, dynamicObject::hitDelay, Vector3::Normalized(), Orientate(), Object::position, previousPos, target, dynamicObject::velocity, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Thug::Control(), Cashier::Control(), Blindman::Control(), Customer::Control(), and S_Guard::Control().
void NPC::Init () virtual
Initializer.
NPC:
Reimplemented from dynamicObject.
Reimplemented in Manager, S_Guard, Detective, Blindman, Cashier, Thug, and Hobo.
Definition at line 37 of file NPC.cpp.
References BODY, bodyParts, MeshBuilder::GenerateOBJ(), HEAD, Object::ignoreCollision, L_ARM, L_LEG, NUM_BODYPARTS, Object::position, R_ARM, R_LEG, rotation, and rotationDir.
Referenced by Customer::Customer(), and NPC().
void NPC::InitDialogue (const char * filename)
Initialzier for the dialouge.
NPC::InitDialogue
Definition at line 49 of file dialogue.cpp.
References greetings.
Referenced by Customer::Customer(), Hobo::Init(), Thug::Init(), Cashier::Init(), Blindman::Init(), Detective::Init(), S_Guard::Init(), and Manager::Init().
void NPC::InitQuest (const char * filename) virtual
Initialzier for hobo the quest text.
Textbox
Reimplemented in Cashier, and Hobo.
Definition at line 75 of file dialogue.cpp.
References Quest::Accept, Button2D::altNext, Quest::Decline, Button2D::next, and quest.
Referenced by Detective::Init(), and Manager::Init().
void NPC::Orientate (float o, double dt, float speed)
Orientation.
NPC:
Definition at line 77 of file NPC.cpp.
References Vector3::Cross(), Object::orientation, Vector3::SphericalToCartesian(), and Vector3::y.
Referenced by Hobo::Control(), Cashier::Control(), Customer::Control(), Detective::Control(), S_Guard::Control(), Manager::Control(), Goto(), and Update().
void NPC::Orientate (Vector3 t, double dt, float speed)
Overloaded orientation.
NPC:
Definition at line 94 of file NPC.cpp.
References Vector3::Cross(), Vector3::Normalized(), Object::orientation, Object::position, Vector3::SphericalToCartesian(), and Vector3::y.
void NPC::Update (double dt, vector< Object * > object, Player * player) virtual
Update function.
NPC:
Reimplemented from dynamicObject.
Definition at line 262 of file NPC.cpp.
References Animate(), bodyParts, Player::camera, Control(), dynamicObject::health, dynamicObject::hitDelay, Player::hOrientation, Object::ignoreCollision, inConversation, initialPos, Material::kAmbient, Material::kDiffuse, dynamicObject::Knockback(), Camera3::lookAt, Mesh::material, Object::mesh, Application::mouseButton(), NUM_BODYPARTS, Orientate(), Object::orientation, Object::position, dynamicObject::RespondToCollision(), Component::Set(), Vector3::SphericalToCartesian(), target, dynamicObject::UpdateVelocity(), and dynamicObject::velocity.
Field Documentation
Bodypart NPC::bodyParts[NUM_BODYPARTS]
Definition at line 59 of file NPC.h.
Referenced by Customer::Customer(), Init(), Hobo::Init(), Thug::Init(), Cashier::Init(), Blindman::Init(), Detective::Init(), S_Guard::Init(), Manager::Init(), and Update().
vector<TextBox> NPC::clues
Definition at line 66 of file NPC.h.
float NPC::elapsedTime
Definition at line 64 of file NPC.h.
Referenced by Blindman::Control(), Customer::Control(), Goto(), and NPC().
vector<TextBox> NPC::greetings
Definition at line 65 of file NPC.h.
Referenced by Hobo::getConversation(), Cashier::getConversation(), Detective::getConversation(), and InitDialogue().
string NPC::identity
Definition at line 60 of file NPC.h.
Referenced by Customer::Customer(), Hobo::Init(), Thug::Init(), Cashier::Init(), Blindman::Init(), Detective::Init(), S_Guard::Init(), and Manager::Init().
bool NPC::inConversation
Definition at line 68 of file NPC.h.
Referenced by Hobo::getConversation(), Cashier::getConversation(), Detective::getConversation(), and Update().
Vector3 NPC::initialPos
Definition at line 54 of file NPC.h.
Referenced by Blindman::Control(), and Update().
Vector3 NPC::previousPos
Definition at line 57 of file NPC.h.
Referenced by Goto().
Quest* NPC::quest
Definition at line 67 of file NPC.h.
Referenced by Detective::Control(), Manager::Control(), getConversation(), Hobo::getConversation(), Cashier::getConversation(), Detective::getConversation(), Manager::getCriteria(), Detective::Init(), InitQuest(), Hobo::InitQuest(), Cashier::InitQuest(), and NPC().
float NPC::rotation[NUM_BODYPARTS]
Definition at line 61 of file NPC.h.
Referenced by Animate(), Detective::Detective(), Init(), and Manager::Manager().
int NPC::rotationDir[NUM_BODYPARTS]
Definition at line 63 of file NPC.h.
Referenced by Animate(), and Init().
Vector3 NPC::target
Definition at line 58 of file NPC.h.
Referenced by Blindman::Blindman(), Cashier::Cashier(), Hobo::Control(), Thug::Control(), Cashier::Control(), Blindman::Control(), Customer::Control(), Detective::Control(), S_Guard::Control(), Manager::Control(), Customer::Customer(), Detective::Detective(), Goto(), Manager::Manager(), S_Guard::S_Guard(), and Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/NPC.h
MyGraphics/Source/dialogue.cpp
MyGraphics/Source/NPC.cpp