My Application: dynamicObject Class Reference
dynamicObject Class Reference
This class is for the dynamic objects. Mainly used for the crates.
#include <player.h>
Public Member Functions
dynamicObject ()
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float o)
~dynamicObject ()
virtual void Init ()
virtual void Control (double dt, vector< Object * >object, Player *player)
virtual void Update (double dt, vector< Object * >object, Player *player)
dynamicObj update
void UpdateVelocity (double dt)
bool Knockback (Vector3 dir, Vector3 vel)
void RespondToCollision (Vector3 initialPos, vector< Object * >object)
void RespondToCollision (Vector3 initialPos, vector< Object * >object, Player *player)
dynamicObj RespondToCollision
float getHealth ()
Public Member Functions inherited from Object
Object ()
Object (Vector3 p, Vector3 c, Vector3 h)
Basic constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i, bool paid)
virtual ~Object ()
virtual void Update (double dt)
virtual void setPaid (bool p)
virtual bool getPaid ()
virtual float getValue ()
virtual string getIdentity ()
virtual Vector3 getStorePos (Player *player)
Data Fields
Vector3 velocity
float hitDelay
float health
Data Fields inherited from Object
std::string type
Vector3 position
Collision collision
Mesh * mesh
float orientation
float size
bool ignoreCollision
Additional Inherited Members
Static Public Member Functions inherited from Object
static bool checkCollision (Object *a, Object *b)
Collsion checker function.
Detailed Description
This class is for the dynamic objects. Mainly used for the crates.
Class dynamicObject: Object
Definition at line 32 of file player.h.
Constructor & Destructor Documentation
dynamicObject::dynamicObject () inline
Definition at line 35 of file player.h.
dynamicObject::dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh * m) inline
Definition at line 36 of file player.h.
dynamicObject::dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh * m, float o) inline
Definition at line 37 of file player.h.
dynamicObject::~dynamicObject () inline
Definition at line 38 of file player.h.
Member Function Documentation
void dynamicObject::Control (double dt, vector< Object * > object, Player * player) virtual
Reimplemented in Manager, S_Guard, Detective, Customer, Blindman, Cashier, Thug, Hobo, and NPC.
Definition at line 2608 of file PROJECTScene.cpp.
References Player::camera, Player::holding, PROJECTScene::inputDelay, Application::IsKeyPressed(), Camera3::lookAt, Object::position, Camera::target, velocity, and Vector3::y.
Referenced by Update().
float dynamicObject::getHealth () inline virtual
Reimplemented from Object.
Reimplemented in Player.
Definition at line 52 of file player.h.
Referenced by Blindman::Control().
virtual void dynamicObject::Init () inline virtual
Reimplemented in Manager, S_Guard, Detective, Blindman, Cashier, Thug, Hobo, and NPC.
Definition at line 40 of file player.h.
bool dynamicObject::Knockback (Vector3 dir, Vector3 vel) virtual
Reimplemented from Object.
Definition at line 12 of file NPC.cpp.
References health, hitDelay, Vector3::Length(), velocity, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Blindman::Control(), S_Guard::Control(), and NPC::Update().
void dynamicObject::RespondToCollision (Vector3 initialPos, vector< Object * > object)
Referenced by Update(), NPC::Update(), and Player::Update().
void dynamicObject::RespondToCollision (Vector3 initialPos, vector< Object * > object, Player * player)
dynamicObj RespondToCollision
Definition at line 431 of file player.cpp.
References Collision::centre, Object::checkCollision(), Object::collision, CollisionResponse(), Collision::hitbox, Player::holding, Object::ignoreCollision, Player::JUMP, Object::position, Player::state, Object::type, velocity, and Vector3::y.
void dynamicObject::Update (double dt, vector< Object * > object, Player * player) virtual
dynamicObj update
Reimplemented from Object.
Reimplemented in NPC.
Definition at line 411 of file player.cpp.
References Control(), Vector3::Dist(), Object::position, RespondToCollision(), velocity, and Vector3::y.
void dynamicObject::UpdateVelocity (double dt)
Definition at line 184 of file NPC.cpp.
References velocity, Vector3::x, Vector3::y, and Vector3::z.
Referenced by NPC::Update(), and Player::Update().
Field Documentation
float dynamicObject::health
Definition at line 51 of file player.h.
Referenced by Hobo::Init(), Detective::Init(), Manager::Init(), Knockback(), NPC::NPC(), PROJECTScene::Render(), NPC::Update(), Player::Update(), and PROJECTScene::Update().
float dynamicObject::hitDelay
Definition at line 45 of file player.h.
Referenced by Player::Control(), Blindman::Control(), NPC::Goto(), Knockback(), NPC::NPC(), NPC::Update(), and Player::Update().
Vector3 dynamicObject::velocity
Definition at line 43 of file player.h.
Referenced by NPC::Animate(), Control(), Player::Control(), Hobo::Control(), Blindman::Control(), Detective::Control(), Manager::Control(), NPC::Goto(), Knockback(), RespondToCollision(), Update(), NPC::Update(), Player::Update(), and UpdateVelocity().
The documentation for this class was generated from the following files:
MyGraphics/Source/player.h
MyGraphics/Source/NPC.cpp
MyGraphics/Source/player.cpp
MyGraphics/Source/PROJECTScene.cpp