My Application: Doorway Class Reference
Doorway Class Reference
This class is for the automatic sliding doors in the game.
#include <player.h>
Public Member Functions
Doorway ()
void Init (Vector3 p, Object D, Object B1, Object B2, Object R)
void Init (Vector3 p, Object D, Object R)
~Doorway ()
void ButtonUpdate (double dt, vector< Object * >object, Player *players)
Doorway button update for elevator.
void RangeUpdate (double dt, vector< Object * >object, Player *player)
Doorway rangebox update /*.
void Update (double dt, vector< Object * >object, Player *player)
Doorway update.
Data Fields
Object Door [2]
Vector3 doorPosition [2]
Object Button [2]
Object Range
Mesh * buttonStatus [2]
bool open
bool close
float elapsedTime
Detailed Description
This class is for the automatic sliding doors in the game.
Class Doorway
Definition at line 145 of file player.h.
Constructor & Destructor Documentation
Doorway::Doorway () inline
Definition at line 148 of file player.h.
Doorway::~Doorway () inline
Definition at line 174 of file player.h.
Member Function Documentation
void Doorway::ButtonUpdate (double dt, vector< Object * > object, Player * players)
Doorway button update for elevator.
Definition at line 576 of file player.cpp.
References buttonStatus, Player::camera, close, elapsedTime, Player::holding, Application::IsKeyPressed(), Camera3::lookAt, and open.
Referenced by PROJECTScene::Update().
void Doorway::Init (Vector3 p, Object D, Object B1, Object B2, Object R) inline
Definition at line 150 of file player.h.
References Object::collision, MeshBuilder::GenerateOBJ(), Collision::hitbox, LoadTGA(), Object::mesh, Button::position, Object::position, and Vector3::x.
Referenced by PROJECTScene::DarrenInit().
void Doorway::Init (Vector3 p, Object D, Object R) inline
Definition at line 164 of file player.h.
References Object::collision, Collision::hitbox, Object::position, and Vector3::x.
void Doorway::RangeUpdate (double dt, vector< Object * > object, Player * player)
Doorway rangebox update /*.
Definition at line 549 of file player.cpp.
References Object::checkCollision(), close, entrance, open, and Range.
Referenced by PROJECTScene::Update().
void Doorway::Update (double dt, vector< Object * > object, Player * player)
Doorway update.
Definition at line 483 of file player.cpp.
References buttonStatus, Object::checkCollision(), close, Object::collision, Door, doorPosition, elapsedTime, Collision::hitbox, open, Object::position, and Vector3::x.
Referenced by PROJECTScene::Update().
Field Documentation
Object Doorway::Button[2]
Definition at line 178 of file player.h.
Referenced by PROJECTScene::DarrenInit().
Mesh* Doorway::buttonStatus[2]
Definition at line 180 of file player.h.
Referenced by ButtonUpdate(), and Update().
bool Doorway::close
Definition at line 181 of file player.h.
Referenced by ButtonUpdate(), RangeUpdate(), PROJECTScene::Update(), and Update().
Object Doorway::Door[2]
Definition at line 174 of file player.h.
Referenced by PROJECTScene::DarrenInit(), and Update().
Vector3 Doorway::doorPosition[2]
Definition at line 177 of file player.h.
Referenced by Update().
float Doorway::elapsedTime
Definition at line 182 of file player.h.
Referenced by ButtonUpdate(), and Update().
bool Doorway::open
Definition at line 181 of file player.h.
Referenced by ButtonUpdate(), RangeUpdate(), PROJECTScene::Update(), and Update().
Object Doorway::Range
Definition at line 179 of file player.h.
Referenced by RangeUpdate(), and PROJECTScene::Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/player.h
MyGraphics/Source/player.cpp