My Application: MENUScene Class Reference
MENUScene Class Reference
The MENUScene class.
#include <MENUScene.h>
Public Member Functions
MENUScene ()
This is the constructor.
~MENUScene ()
virtual void Init ()
void InitJunk ()
Initializers.
virtual void Update (double dt)
Update.
virtual void Render ()
Render.
virtual void Exit ()
Exit.
int soundInit ()
the sound initializer for the menu scene
Public Member Functions inherited from Scene
Scene ()
virtual ~Scene ()
Data Fields
Button buttons [4]
int select
Data Fields inherited from Scene
std::string type
Static Public Attributes
static float inputDelay = 0.f
Private Types
enum GEOMETRY_TYPE {
GEO_AXES = 0, GEO_LEFT, GEO_RIGHT, GEO_TOP,
GEO_BOTTOM, GEO_FRONT, GEO_BACK, GEO_LIGHTBALL,
GEO_QUAD, GEO_KNIFE, GEO_HEART, GEO_SPRINT,
GEO_JUMP, GEO_TEXT, GEO_LINE, GEO_CUBE,
GEO_BIGCUBE, GEO_HOLD, GEO_OVERLAY, GEO_TEXTBOX,
GEO_TEXTBOX2, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHTENABLED,
U_LIGHT0_POSITION, U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC,
U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION, U_LIGHT2_COLOR,
U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ,
U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER,
U_LIGHT2_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE,
U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void RenderSkybox ()
Rendering the skybox.
void RenderCrosshair ()
Render Crosshair.
void InitSuperMarket ()
void RenderScene ()
Render.
void RenderMesh (Mesh *mesh, bool enableLight)
Render Mesh.
void RenderText (Mesh *mesh, std::string text, Color color)
RenderText.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
float getTextWidth (string t)
Get text width.
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Light light [3]
Camera3 * camera
Player player
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
The MENUScene class.
Class MENUScene: scene
Definition at line 59 of file MENUScene.h.
Member Enumeration Documentation
enum MENUScene::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_LIGHTBALL
GEO_QUAD
GEO_KNIFE
GEO_HEART
GEO_SPRINT
GEO_JUMP
GEO_TEXT
GEO_LINE
GEO_CUBE
GEO_BIGCUBE
GEO_HOLD
GEO_OVERLAY
GEO_TEXTBOX
GEO_TEXTBOX2
NUM_GEOMETRY
Definition at line 61 of file MENUScene.h.
enum MENUScene::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHTENABLED
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 86 of file MENUScene.h.
Constructor & Destructor Documentation
MENUScene::MENUScene ()
This is the constructor.
MENUScene:
Definition at line 31 of file MENUScene.cpp.
References Scene::type.
MENUScene::~MENUScene ()
Definition at line 36 of file MENUScene.cpp.
Member Function Documentation
void MENUScene::Exit () virtual
Exit.
MENUScene:
Implements Scene.
Definition at line 752 of file MENUScene.cpp.
References m_programID, m_vertexArrayID, and irrklang::ISoundEngine::stopAllSounds().
float MENUScene::getTextWidth (string text) private
Get text width.
MENUScene:
Definition at line 673 of file MENUScene.cpp.
Referenced by Render().
void MENUScene::Init () virtual
Implements Scene.
Definition at line 119 of file MENUScene.cpp.
References buttons, Player::camera, camera, MeshBuilder::GenerateCube(), MeshBuilder::GenerateCubeOnPlane(), MeshBuilder::GenerateLine(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateText(), MeshBuilder::GenerateXYQuad(), GEO_BIGCUBE, GEO_CUBE, GEO_HEART, GEO_HOLD, GEO_JUMP, GEO_KNIFE, GEO_LINE, GEO_OVERLAY, GEO_QUAD, GEO_SPRINT, GEO_TEXT, GEO_TEXTBOX, InitJunk(), Light::kC, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, MS::LoadMatrix(), LoadTGA(), m_parameters, m_vertexArrayID, main, meshList, Button::name, player, Light::position, Button::position, Light::power, projectionStack, select, Position::Set(), Mtx44::SetToPerspective(), soundInit(), startupDelay, Mesh::textureID, Scene::type, Light::type, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POWER, U_LIGHT0_TYPE, and U_NUMLIGHTS.
void MENUScene::InitJunk ()
Initializers.
MENUScene:
Definition at line 45 of file MENUScene.cpp.
References MeshBuilder::GenerateAxes(), MeshBuilder::GenerateQuad(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, LoadShaders(), LoadTGA(), m_parameters, m_programID, meshList, Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
Referenced by Init().
void MENUScene::InitSuperMarket () private
void MENUScene::Render () virtual
Render.
MENUScene:
Implements Scene.
Definition at line 410 of file MENUScene.cpp.
References buttons, camera, cheat, cheats, controls, Camera3::fov, GEO_OVERLAY, GEO_QUAD, GEO_TEXT, GEO_TEXTBOX, getTextWidth(), MS::LoadIdentity(), MS::LoadMatrix(), MS::LookAt(), main, meshList, modelStack, MS::PopMatrix(), Camera::position, projectionStack, MS::PushMatrix(), RenderMesh(), RenderScene(), RenderText(), MS::Scale(), select, Mtx44::SetToOrtho(), Mtx44::SetToPerspective(), Camera::target, MS::Translate(), Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void MENUScene::RenderCrosshair () private
Render Crosshair.
MENUScene:
Definition at line 818 of file MENUScene.cpp.
References GEO_LINE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), and MS::Translate().
void MENUScene::RenderMesh (Mesh * mesh, bool enableLight) private
Render Mesh.
MENUScene:
Definition at line 525 of file MENUScene.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderCrosshair(), and RenderSkybox().
void MENUScene::RenderScene () private
Render.
MENUScene:
Definition at line 372 of file MENUScene.cpp.
References camera, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, m_parameters, modelStack, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderSkybox(), MS::Scale(), Light::spotDirection, MS::Top(), MS::Translate(), Scene::type, U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, viewStack, Position::x, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void MENUScene::RenderSkybox () private
Rendering the skybox.
MENUScene:
Definition at line 767 of file MENUScene.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), and MS::Translate().
Referenced by RenderScene().
void MENUScene::RenderText (Mesh * mesh, std::string text, Color color) private
RenderText.
MENUScene:
Definition at line 575 of file MENUScene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void MENUScene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
int MENUScene::soundInit ()
the sound initializer for the menu scene
Class MENUScene::soundInit
Definition at line 37 of file audio.cpp.
References irrklang::createIrrKlangDevice().
Referenced by Init().
void MENUScene::Update (double dt) virtual
Update.
MENUScene:
Implements Scene.
Definition at line 233 of file MENUScene.cpp.
References camera, cheat, cheats, controls, inputDelay, irrklang::ISoundEngine::isCurrentlyPlaying(), Application::IsKeyPressed(), lastKey, main, Application::mouseScroll, Camera3::orientation, play, irrklang::ISoundEngine::play2D(), quit, select, selectDelay, startupDelay, and Camera3::Update().
Field Documentation
Button MENUScene::buttons[4]
Definition at line 128 of file MENUScene.h.
Referenced by Init(), and Render().
Camera3* MENUScene::camera private
Definition at line 144 of file MENUScene.h.
Referenced by Init(), Render(), RenderScene(), and Update().
float MENUScene::inputDelay = 0.f static
Definition at line 126 of file MENUScene.h.
Referenced by Update().
Light MENUScene::light[3] private
Definition at line 137 of file MENUScene.h.
Referenced by Init(), and RenderScene().
unsigned MENUScene::m_parameters[U_TOTAL] private
Definition at line 135 of file MENUScene.h.
Referenced by Init(), InitJunk(), RenderMesh(), RenderScene(), and RenderText().
unsigned MENUScene::m_programID private
Definition at line 134 of file MENUScene.h.
Referenced by Exit(), and InitJunk().
unsigned MENUScene::m_vertexArrayID private
Definition at line 132 of file MENUScene.h.
Referenced by Exit(), and Init().
Mesh* MENUScene::meshList[NUM_GEOMETRY] private
Definition at line 133 of file MENUScene.h.
Referenced by Init(), InitJunk(), Render(), RenderCrosshair(), and RenderSkybox().
MS MENUScene::modelStack private
Definition at line 147 of file MENUScene.h.
Referenced by Render(), RenderCrosshair(), RenderMesh(), RenderScene(), RenderSkybox(), and RenderText().
Player MENUScene::player private
Definition at line 145 of file MENUScene.h.
Referenced by Init().
MS MENUScene::projectionStack private
Definition at line 147 of file MENUScene.h.
Referenced by Init(), Render(), RenderMesh(), and RenderText().
int MENUScene::select
Definition at line 129 of file MENUScene.h.
Referenced by Init(), Render(), and Update().
MS MENUScene::viewStack private
Definition at line 147 of file MENUScene.h.
Referenced by Render(), RenderMesh(), RenderScene(), and RenderText().
The documentation for this class was generated from the following files:
MyGraphics/Source/MENUScene.h
MyGraphics/Source/audio.cpp
MyGraphics/Source/MENUScene.cpp