My Application: Customer Class Reference
Customer Class Reference
This is the customer class for the not important npc.
#include <NPC.h>
Public Member Functions
Customer ()
Customer (vector< NPCTarget > t, string name, unsigned tID, float d)
~Customer ()
virtual void Control (double dt, vector< Object * >object, Player *player)
Customer Control.
Public Member Functions inherited from NPC
NPC (void)
virtual ~NPC (void)
string getIdentity ()
virtual bool getCriteria ()
virtual void Init ()
Initializer.
virtual TextBox * getConversation (Player *player)
void InitDialogue (const char *filename)
Initialzier for the dialouge.
virtual void InitQuest (const char *filename)
Initialzier for hobo the quest text.
void Update (double dt, vector< Object * >object, Player *player)
Update function.
void Orientate (float o, double dt, float speed)
Orientation.
void Orientate (Vector3 t, double dt, float speed)
Overloaded orientation.
void Goto (Vector3 destination, double dt, float turn, float speed)
Go to function.
void Animate (double dt, float speed)
Animation.
void Animate (double dt, float speed, float limit)
Overloaded animate.
Public Member Functions inherited from dynamicObject
dynamicObject ()
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float o)
~dynamicObject ()
void UpdateVelocity (double dt)
bool Knockback (Vector3 dir, Vector3 vel)
void RespondToCollision (Vector3 initialPos, vector< Object * >object)
void RespondToCollision (Vector3 initialPos, vector< Object * >object, Player *player)
dynamicObj RespondToCollision
float getHealth ()
Public Member Functions inherited from Object
Object ()
Object (Vector3 p, Vector3 c, Vector3 h)
Basic constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i, bool paid)
virtual ~Object ()
virtual void Update (double dt)
virtual void setPaid (bool p)
virtual bool getPaid ()
virtual float getValue ()
virtual Vector3 getStorePos (Player *player)
Data Fields
int index
float decisionTime
float tOrientation
vector< NPCTarget > targets
Data Fields inherited from NPC
Vector3 initialPos
Vector3 previousPos
Vector3 target
Bodypart bodyParts [NUM_BODYPARTS]
string identity
float rotation [NUM_BODYPARTS]
int rotationDir [NUM_BODYPARTS]
float elapsedTime
vector< TextBox > greetings
vector< TextBox > clues
Quest * quest
bool inConversation
Data Fields inherited from dynamicObject
Vector3 velocity
float hitDelay
float health
Data Fields inherited from Object
std::string type
Vector3 position
Collision collision
Mesh * mesh
float orientation
float size
bool ignoreCollision
Additional Inherited Members
Public Types inherited from NPC
enum BodyParts {
HEAD, BODY, L_ARM, R_ARM,
L_LEG, R_LEG, NUM_BODYPARTS
}
Static Public Member Functions inherited from Object
static bool checkCollision (Object *a, Object *b)
Collsion checker function.
Detailed Description
This is the customer class for the not important npc.
Class Customer: NPC
Definition at line 275 of file NPC.h.
Constructor & Destructor Documentation
Customer::Customer () inline
Definition at line 278 of file NPC.h.
References NPC::Init(), NPC::InitDialogue(), Object::orientation, Object::position, NPC::target, and Vector3::y.
Customer::Customer (vector< NPCTarget > t, string name, unsigned tID, float d) inline
Definition at line 286 of file NPC.h.
References NPC::bodyParts, decisionTime, NPC::identity, Bodypart::identity, index, NPC::InitDialogue(), Object::mesh, NPC::NUM_BODYPARTS, Object::orientation, Object::position, NPC::target, targets, Mesh::textureID, tOrientation, and Vector3::y.
Customer::~Customer () inline
Definition at line 310 of file NPC.h.
Member Function Documentation
void Customer::Control (double dt, vector< Object * > object, Player * player) virtual
Customer Control.
NPC:
Reimplemented from NPC.
Definition at line 518 of file NPC.cpp.
References NPC::Animate(), decisionTime, NPC::elapsedTime, NPC::Goto(), index, NPC::Orientate(), Object::position, NPC::target, targets, tOrientation, and Vector3::y.
Field Documentation
float Customer::decisionTime
Definition at line 313 of file NPC.h.
Referenced by Control(), and Customer().
int Customer::index
Definition at line 310 of file NPC.h.
Referenced by Control(), and Customer().
vector<NPCTarget> Customer::targets
Definition at line 315 of file NPC.h.
Referenced by Control(), and Customer().
float Customer::tOrientation
Definition at line 314 of file NPC.h.
Referenced by Control(), and Customer().
The documentation for this class was generated from the following files:
MyGraphics/Source/NPC.h
MyGraphics/Source/NPC.cpp