My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateLine (const std::string &meshName, Color color, float length)
static Mesh * GenerateQuad (const std::string &meshName, Color color, float lengthX, float lengthZ, int repeat)
Generate the vertices of a quad; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateXYQuad (const std::string &meshName, Color color, float lengthX, float lengthY, int repeat)
static Mesh * GenerateCubeOnPlane (const std::string &meshName, Color color, float lengthX, float lengthY, float lengthZ, int repeat)
static Mesh * GenerateCube (const std::string &meshName, Color color, float lengthX, float lengthY, float lengthZ, int repeat)
Generate the vertices of a cube; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshName, Color color, float radius)
Generate the vertices of a circle; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateRing (const std::string &meshName, Color color, float radius)
Generate the vertices of a ring; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateSphere (const std::string &meshName, Color color, unsigned numStack, unsigned numSlice, float radius)
Generate the vertices of a sphere; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateHemi (const std::string &meshName, Color color, unsigned numStack, unsigned numSlice, float radius)
Generate the vertices of a hemisphere; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCone (const std::string &meshName, Color color, unsigned numStack, unsigned numSlice, float radius)
static Mesh * GenerateCylinder (const std::string &meshName, Color color, unsigned numSlice, float height, float radius)
Generate the vertices of a cylinder; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCylinder (const std::string &meshName, Color colorBot, Color colorTop, unsigned numSlice, float height, float radius)
static Mesh * GenerateCapsule (const std::string &meshName, Color color, unsigned numStack, unsigned numSlice, float height, float radius)
Generate the vertices of a capsule (cylinder with hemisphere at top & bottom); Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateTorus (const std::string &meshName, Color color, unsigned numStack, unsigned numSlice, float outerR, float innerR)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 23 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 29 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by MENUScene::InitJunk(), and PROJECTScene::InitJunk().
Mesh * MeshBuilder::GenerateCapsule (const std::string & meshName, Color color, unsigned numStack, unsigned numSlice, float height, float radius) static
Generate the vertices of a capsule (cylinder with hemisphere at top & bottom); Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of capsule
numStack - number of vertical components(stacks) of capsule
numSlice - number of horizontal components(slices) of capsule
height - height of capsule
radius - radius of capsule
Returns
Pointer to mesh storing VBO/IBO of capsule
Definition at line 1009 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), sphereX(), sphereY(), sphereZ(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCircle (const std::string & meshName, Color color, float radius) static
Generate the vertices of a circle; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of circle
radius - radius of circle
Returns
Pointer to mesh storing VBO/IBO of circle
Definition at line 484 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, PI, Vertex::pos, Position::Set(), and Mesh::vertexBuffer.
Referenced by Particles::Particles().
Mesh * MeshBuilder::GenerateCone (const std::string & meshName, Color color, unsigned numStack, unsigned numSlice, float radius) static
Definition at line 739 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), sphereY(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color, float lengthX, float lengthY, float lengthZ, int repeat) static
Generate the vertices of a cube; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of cube
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 254 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by PROJECTScene::DarrenInit(), MENUScene::Init(), PROJECTScene::Init(), PROJECTScene::JeremiahInit(), PROJECTScene::JessicaInit(), NPC::NPC(), and PROJECTScene::RicssonInit().
Mesh * MeshBuilder::GenerateCubeOnPlane (const std::string & meshName, Color color, float lengthX, float lengthY, float lengthZ, int repeat) static
Definition at line 363 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by MENUScene::Init(), PROJECTScene::Init(), and PROJECTScene::RicssonInit().
Mesh * MeshBuilder::GenerateCylinder (const std::string & meshName, Color color, unsigned numSlice, float height, float radius) static
Generate the vertices of a cylinder; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of cylinder
numSlice - number of sides the cylinder has
height - height of cylinder
radius - radius of cylinder
Returns
Pointer to mesh storing VBO/IBO of cylinder
Definition at line 822 of file MeshBuilder.cpp.
References Vertex::color, cylinderX(), cylinderZ(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCylinder (const std::string & meshName, Color colorBot, Color colorTop, unsigned numSlice, float height, float radius) static
Definition at line 906 of file MeshBuilder.cpp.
References Vertex::color, cylinderX(), cylinderZ(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateHemi (const std::string & meshName, Color color, unsigned numStack, unsigned numSlice, float radius) static
Generate the vertices of a hemisphere; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of cube
numStack - number of vertical components(stacks) of hemisphere
numSlice - number of horizontal components(slices) of hemisphere
radius - radius of hemisphere
Returns
Pointer to mesh storing VBO/IBO of hemisphere
Definition at line 672 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), sphereX(), sphereY(), sphereZ(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateLine (const std::string & meshName, Color color, float length) static
Definition at line 79 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), and Mesh::vertexBuffer.
Referenced by MENUScene::Init(), and PROJECTScene::Init().
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 1184 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by PROJECTScene::DarrenInit(), Vending::generateDrink(), NPC::Init(), MENUScene::Init(), PROJECTScene::Init(), Doorway::Init(), PROJECTScene::JeremiahInit(), PROJECTScene::JessicaInit(), and PROJECTScene::RicssonInit().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color, float lengthX, float lengthZ, int repeat) static
Generate the vertices of a quad; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of quad
lengthX - length of quad
lengthZ - width of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 130 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by MENUScene::InitJunk(), PROJECTScene::InitJunk(), and PROJECTScene::JeremiahInit().
Mesh * MeshBuilder::GenerateRing (const std::string & meshName, Color color, float radius) static
Generate the vertices of a ring; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of ring
radius - radius of ring
Returns
Pointer to mesh storing VBO/IBO of ring
Definition at line 533 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, PI, Vertex::pos, Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, unsigned numStack, unsigned numSlice, float radius) static
Generate the vertices of a sphere; Use color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
color - color of cube
numStack - number of vertical components(stacks) of sphere
numSlice - number of horizontal components(slices) of sphere
radius - radius of sphere
Returns
Pointer to mesh storing VBO/IBO of sphere
Definition at line 609 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), sphereX(), sphereY(), sphereZ(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 1123 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by MENUScene::Init(), and PROJECTScene::Init().
Mesh * MeshBuilder::GenerateTorus (const std::string & meshName, Color color, unsigned numStack, unsigned numSlice, float outerR, float innerR) static
Definition at line 1067 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateXYQuad (const std::string & meshName, Color color, float lengthX, float lengthY, int repeat) static
Definition at line 185 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by MENUScene::Init(), Inventory::Init(), PROJECTScene::Init(), PROJECTScene::JeremiahInit(), and PROJECTScene::JessicaInit().
The documentation for this class was generated from the following files:
MyGraphics/Source/MeshBuilder.h
MyGraphics/Source/MeshBuilder.cpp