My Application: Vending Class Reference
Vending Class Reference
Vending class which is used for initializing the vending machine and its functions.
#include <collision.h>
Public Member Functions
Vending ()
Vending (Object D)
~Vending ()
Item * generateDrink ()
Data Fields
float price
Object Drink
Detailed Description
Vending class which is used for initializing the vending machine and its functions.
Class Vending:
Definition at line 151 of file collision.h.
Constructor & Destructor Documentation
Vending::Vending () inline
Definition at line 154 of file collision.h.
Vending::Vending (Object D) inline
Definition at line 155 of file collision.h.
References Drink, price, and Object::type.
Vending::~Vending () inline
Definition at line 160 of file collision.h.
Member Function Documentation
Item* Vending::generateDrink () inline
Definition at line 163 of file collision.h.
References MeshBuilder::GenerateOBJ(), LoadTGA(), and Mesh::textureID.
Referenced by PROJECTScene::Update().
Field Documentation
Object Vending::Drink
Definition at line 172 of file collision.h.
Referenced by PROJECTScene::JessicaInit(), and Vending().
float Vending::price
Definition at line 160 of file collision.h.
Referenced by PROJECTScene::Render(), PROJECTScene::Update(), and Vending().
The documentation for this class was generated from the following file:
MyGraphics/Source/collision.h