My Application: PROJECTScene Class Reference
PROJECTScene Class Reference
#include <PROJECTScene.h>
Public Member Functions
PROJECTScene ()
~PROJECTScene ()
virtual void Init ()
void InitJunk ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
void RicssonInit ()
void JeremiahInit ()
void JessicaInit ()
void DarrenInit ()
int soundInit ()
int soundUpdate (Player player)
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Static Public Attributes
static float inputDelay = 0.f
Private Types
enum GEOMETRY_TYPE {
GEO_AXES = 0, GEO_LEFT, GEO_RIGHT, GEO_TOP,
GEO_BOTTOM, GEO_FRONT, GEO_BACK, GEO_LIGHTBALL,
GEO_QUAD, GEO_KNIFE, GEO_HEART, GEO_SPRINT,
GEO_JUMP, GEO_TEXT, GEO_LINE, GEO_CUBE,
GEO_BIGCUBE, GEO_HOLD, GEO_CCTV, GEO_CCTV_CORNER,
GEO_TEXTBOX, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHTENABLED,
U_LIGHT0_POSITION, U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC,
U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION, U_LIGHT2_COLOR,
U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ,
U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER,
U_LIGHT2_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE,
U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void RenderSkybox ()
void RenderCrosshair ()
void InitSuperMarket ()
void RenderScene ()
void RenderCCTVUI (int number)
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
float getTextWidth (string t)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
TextBox * textbox
vector< OnScreenText * > text
vector< OnScreenText * > text2D
vector< NPC * > character
vector< Object * > object
vector< Particles * > blood
Doorway doorway
Doorway doorway2
Doorway AutoDoor
ATM Bank
Vending Machine
Security controlPanel
Light light [3]
Camera3 * camera
Player player
MS modelStack
MS viewStack
MS projectionStack
Additional Inherited Members
Data Fields inherited from Scene
bool pause
Detailed Description
Definition at line 64 of file PROJECTScene.h.
Member Enumeration Documentation
enum PROJECTScene::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_LIGHTBALL
GEO_QUAD
GEO_KNIFE
GEO_HEART
GEO_SPRINT
GEO_JUMP
GEO_TEXT
GEO_LINE
GEO_CUBE
GEO_BIGCUBE
GEO_HOLD
GEO_CCTV
GEO_CCTV_CORNER
GEO_TEXTBOX
NUM_GEOMETRY
Definition at line 66 of file PROJECTScene.h.
enum PROJECTScene::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHTENABLED
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 91 of file PROJECTScene.h.
Constructor & Destructor Documentation
PROJECTScene::PROJECTScene ()
Definition at line 16 of file PROJECTScene.cpp.
PROJECTScene::~PROJECTScene ()
Definition at line 19 of file PROJECTScene.cpp.
Member Function Documentation
void PROJECTScene::DarrenInit ()
Definition at line 967 of file PROJECTScene.cpp.
References AutoDoor, Bank, Doorway::Button, ATM::Deposit, Doorway::Door, doorway, doorway2, MeshBuilder::GenerateCube(), MeshBuilder::GenerateOBJ(), Doorway::Init(), LoadTGA(), Mesh::textureID, ATM::Withdraw, Vector3::x, x, Vector3::y, and Vector3::z.
Referenced by Init().
void PROJECTScene::Exit () virtual
Implements Scene.
Definition at line 2541 of file PROJECTScene.cpp.
References m_programID, and m_vertexArrayID.
float PROJECTScene::getTextWidth (string t) private
Definition at line 2474 of file PROJECTScene.cpp.
Referenced by Render(), RenderCCTVUI(), and RenderScene().
void PROJECTScene::Init () virtual
Implements Scene.
Definition at line 1088 of file PROJECTScene.cpp.
References Player::camera, camera, DarrenInit(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateCubeOnPlane(), MeshBuilder::GenerateLine(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateText(), MeshBuilder::GenerateXYQuad(), GEO_BIGCUBE, GEO_CCTV, GEO_CCTV_CORNER, GEO_CUBE, GEO_HEART, GEO_HOLD, GEO_JUMP, GEO_KNIFE, GEO_LINE, GEO_QUAD, GEO_SPRINT, GEO_TEXT, GEO_TEXTBOX, InitJunk(), JeremiahInit(), JessicaInit(), Light::kC, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, MS::LoadMatrix(), LoadTGA(), m_parameters, m_vertexArrayID, meshList, player, Light::position, Light::power, projectionStack, RicssonInit(), Position::Set(), Mtx44::SetToPerspective(), soundInit(), text2D, textbox, Mesh::textureID, Light::type, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POWER, U_LIGHT0_TYPE, and U_NUMLIGHTS.
void PROJECTScene::InitJunk ()
Definition at line 22 of file PROJECTScene.cpp.
References MeshBuilder::GenerateAxes(), MeshBuilder::GenerateQuad(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, LoadShaders(), LoadTGA(), m_parameters, m_programID, meshList, Scene::pause, Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
Referenced by Init().
void PROJECTScene::InitSuperMarket () private
void PROJECTScene::JeremiahInit ()
Definition at line 222 of file PROJECTScene.cpp.
References character, MeshBuilder::GenerateCube(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateXYQuad(), LoadTGA(), Mesh::textureID, Vector3::x, x, Vector3::y, and Vector3::z.
Referenced by Init().
void PROJECTScene::JessicaInit ()
Definition at line 518 of file PROJECTScene.cpp.
References controlPanel, Vending::Drink, MeshBuilder::GenerateCube(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateXYQuad(), LoadTGA(), Machine, Mesh::textureID, Security::TV, Vector3::x, x, Vector3::y, and Vector3::z.
Referenced by Init().
void PROJECTScene::Render () virtual
Implements Scene.
Definition at line 1885 of file PROJECTScene.cpp.
References animateHeart, TextBox::apparentext, Bank, Player::bobbingX, Player::bobbingY, Player::camera, camera, CCTV, Security::CCTVs, controlPanel, ATM::Deposit, Camera3::fov, fps, GEO_HEART, GEO_JUMP, GEO_QUAD, GEO_SPRINT, GEO_TEXT, GEO_TEXTBOX, TextBox::getAccept(), TextBox::getDecline(), Player::getHealth(), Inventory::getHolding(), Player::getRenderWallet(), getTextWidth(), Player::holding, Player::inventory, Player::isEating(), Slot::item, Player::jump, MS::LoadIdentity(), MS::LoadMatrix(), Camera3::lookAt, MS::LookAt(), Machine, Slot::mesh, Selector::mesh, meshList, modelStack, player, MS::PopMatrix(), Camera::position, Button2D::position, TextBox::position, Slot::position, Vending::price, projectionStack, MS::PushMatrix(), RenderCCTVUI(), RenderCrosshair(), RenderMesh(), RenderScene(), RenderText(), MS::Rotate(), MS::Scale(), Selector::selectedSlot, Inventory::selector, Mtx44::SetToOrtho(), Mtx44::SetToPerspective(), showLevel, Inventory::slots, Player::speed, Camera::target, Button2D::text, TextBox::text, text2D, textbox, MS::Translate(), Object::type, TextBox::type, Camera::up, Player::value, viewStack, ATM::Withdraw, Vector3::x, x, Vector3::y, and Vector3::z.
void PROJECTScene::RenderCCTVUI (int number) private
Definition at line 1817 of file PROJECTScene.cpp.
References CCTV, GEO_CCTV, GEO_CCTV_CORNER, GEO_TEXT, getTextWidth(), MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), RenderText(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void PROJECTScene::RenderCrosshair () private
Definition at line 2592 of file PROJECTScene.cpp.
References GEO_LINE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), and MS::Translate().
Referenced by Render().
void PROJECTScene::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 2302 of file PROJECTScene.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderCCTVUI(), RenderCrosshair(), RenderScene(), and RenderSkybox().
void PROJECTScene::RenderScene () private
Definition at line 1607 of file PROJECTScene.cpp.
References Bank, blood, Collision::boundingBox, Player::camera, camera, Collision::centre, character, Object::collision, GEO_AXES, GEO_HOLD, GEO_TEXT, ATM::getSavings(), getTextWidth(), Player::holding, Application::IsKeyPressed(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, Camera3::look, Camera3::lookAt, m_parameters, meshList, modelStack, Camera3::orientation, player, MS::PopMatrix(), Camera::position, Light::position, Object::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), RenderText(), MS::Rotate(), MS::Scale(), Light::spotDirection, Camera::target, text, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, viewStack, Position::x, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void PROJECTScene::RenderSkybox () private
Definition at line 2548 of file PROJECTScene.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), and MS::Translate().
Referenced by RenderScene().
void PROJECTScene::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 2345 of file PROJECTScene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), RenderCCTVUI(), and RenderScene().
void PROJECTScene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
void PROJECTScene::RicssonInit ()
Definition at line 94 of file PROJECTScene.cpp.
References Collision::boundingBox, Object::collision, MeshBuilder::GenerateCube(), MeshBuilder::GenerateCubeOnPlane(), MeshBuilder::GenerateOBJ(), Collision::hitbox, LoadTGA(), player, Mesh::textureID, Vector3::x, x, Vector3::y, and Vector3::z.
Referenced by Init().
int PROJECTScene::soundInit ()
Definition at line 6 of file audio.cpp.
References irrklang::createIrrKlangDevice().
Referenced by Init().
int PROJECTScene::soundUpdate (Player player)
Definition at line 27 of file audio.cpp.
References Player::hOrientation, Object::position, irrklang::ISoundEngine::setListenerPosition(), Vector3::SphericalToCartesian(), Player::vOrientation, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void PROJECTScene::Update (double dt) virtual
Implements Scene.
Definition at line 1192 of file PROJECTScene.cpp.
References Button2D::altNext, animateHeart, animateHeartDir, TextBox::apparentext, AutoDoor, Bank, blood, Doorway::ButtonUpdate(), Player::camera, camera, CCTV, Security::CCTVs, character, Object::checkCollision(), Inventory::Checkout(), Inventory::checkPrice(), Doorway::close, controlPanel, Inventory::Delete(), ATM::deposit(), ATM::Deposit, doorway, doorway2, fps, Vending::generateDrink(), TextBox::GenerateText(), TextBox::getAccept(), TextBox::getDecline(), Player::getHealth(), Inventory::getHolding(), Player::holding, Player::inConversation, inputDelay, Inventory::Insert(), Player::inventory, Application::IsKeyPressed(), Slot::item, Camera3::lookAt, Camera3::lookingAt(), Machine, Application::mouseButton(), Application::mouseScroll, Camera3::Move(), Button2D::next, Doorway::open, Scene::pause, pauseDelay, irrklang::ISoundEngine::play2D(), player, Button2D::position, Object::position, Vending::price, Doorway::Range, Doorway::RangeUpdate(), Inventory::Remove(), selectDelay, Selector::selectedSlot, Inventory::selector, showLevel, soundUpdate(), stopCamera, TextBox::text, text, text2D, textbox, TextBox::triggerQuest(), Wallet::trueValue, Object::type, TextBox::type, Camera3::Update(), TextBox::Update(), Player::Update(), Doorway::Update(), Inventory::wallet, ATM::withdraw(), ATM::Withdraw, x, Vector3::y, and Camera3::Zoom().
Field Documentation
Doorway PROJECTScene::AutoDoor private
Definition at line 153 of file PROJECTScene.h.
Referenced by DarrenInit(), and Update().
ATM PROJECTScene::Bank private
Definition at line 154 of file PROJECTScene.h.
Referenced by DarrenInit(), Render(), RenderScene(), and Update().
vector<Particles*> PROJECTScene::blood private
Definition at line 149 of file PROJECTScene.h.
Referenced by RenderScene(), and Update().
Camera3* PROJECTScene::camera private
Definition at line 166 of file PROJECTScene.h.
Referenced by Init(), Render(), RenderScene(), and Update().
vector<NPC*> PROJECTScene::character private
Definition at line 147 of file PROJECTScene.h.
Referenced by JeremiahInit(), RenderScene(), and Update().
Security PROJECTScene::controlPanel private
Definition at line 156 of file PROJECTScene.h.
Referenced by JessicaInit(), Render(), and Update().
Doorway PROJECTScene::doorway private
Definition at line 151 of file PROJECTScene.h.
Referenced by DarrenInit(), and Update().
Doorway PROJECTScene::doorway2 private
Definition at line 152 of file PROJECTScene.h.
Referenced by DarrenInit(), and Update().
float PROJECTScene::inputDelay = 0.f static
Definition at line 137 of file PROJECTScene.h.
Referenced by dynamicObject::Control(), and Update().
Light PROJECTScene::light[3] private
Definition at line 158 of file PROJECTScene.h.
Referenced by Init(), and RenderScene().
unsigned PROJECTScene::m_parameters[U_TOTAL] private
Definition at line 142 of file PROJECTScene.h.
Referenced by Init(), InitJunk(), RenderMesh(), RenderScene(), and RenderText().
unsigned PROJECTScene::m_programID private
Definition at line 141 of file PROJECTScene.h.
Referenced by Exit(), and InitJunk().
unsigned PROJECTScene::m_vertexArrayID private
Definition at line 139 of file PROJECTScene.h.
Referenced by Exit(), and Init().
Vending PROJECTScene::Machine private
Definition at line 155 of file PROJECTScene.h.
Referenced by JessicaInit(), Render(), and Update().
Mesh* PROJECTScene::meshList[NUM_GEOMETRY] private
Definition at line 140 of file PROJECTScene.h.
Referenced by Init(), InitJunk(), Render(), RenderCCTVUI(), RenderCrosshair(), RenderScene(), and RenderSkybox().
MS PROJECTScene::modelStack private
Definition at line 169 of file PROJECTScene.h.
Referenced by Render(), RenderCCTVUI(), RenderCrosshair(), RenderMesh(), RenderScene(), RenderSkybox(), and RenderText().
vector<Object*> PROJECTScene::object private
Definition at line 148 of file PROJECTScene.h.
Player PROJECTScene::player private
Definition at line 167 of file PROJECTScene.h.
Referenced by Init(), Render(), RenderScene(), RicssonInit(), and Update().
MS PROJECTScene::projectionStack private
Definition at line 169 of file PROJECTScene.h.
Referenced by Init(), Render(), RenderCCTVUI(), RenderMesh(), and RenderText().
vector<OnScreenText*> PROJECTScene::text private
Definition at line 145 of file PROJECTScene.h.
Referenced by RenderScene(), and Update().
vector<OnScreenText*> PROJECTScene::text2D private
Definition at line 146 of file PROJECTScene.h.
Referenced by Init(), Render(), and Update().
TextBox* PROJECTScene::textbox private
Definition at line 144 of file PROJECTScene.h.
Referenced by Init(), Render(), and Update().
MS PROJECTScene::viewStack private
Definition at line 169 of file PROJECTScene.h.
Referenced by Render(), RenderCCTVUI(), RenderMesh(), RenderScene(), and RenderText().
The documentation for this class was generated from the following files:
MyGraphics/Source/PROJECTScene.h
MyGraphics/Source/audio.cpp
MyGraphics/Source/PROJECTScene.cpp