My Application: Player Class Reference
Player Class Reference
This is the player class.
#include <player.h>
Public Types
enum playerStates { JUMP, EATING, KNIFE, TOTAL_STATES }
enum playerValues {
bobbingX, bobbingY, knifeRotation, knifeStrike,
knifeCooldown, eyeLevel, jumpCooldown, eatCooldown,
eatElapsed, TOTAL_VALUES
}
Public Member Functions
Player ()
~Player ()
virtual void Control (double dt, vector< Object * >object)
PLayer Control.
virtual void Update (double dt, vector< Object * >object)
PLayer Update function.
float getRenderWallet ()
float getWallet ()
float getHealth ()
bool isEating ()
Public Member Functions inherited from dynamicObject
dynamicObject ()
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float o)
~dynamicObject ()
virtual void Init ()
virtual void Control (double dt, vector< Object * >object, Player *player)
virtual void Update (double dt, vector< Object * >object, Player *player)
dynamicObj update
void UpdateVelocity (double dt)
bool Knockback (Vector3 dir, Vector3 vel)
void RespondToCollision (Vector3 initialPos, vector< Object * >object)
void RespondToCollision (Vector3 initialPos, vector< Object * >object, Player *player)
dynamicObj RespondToCollision
Public Member Functions inherited from Object
Object ()
Object (Vector3 p, Vector3 c, Vector3 h)
Basic constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i, bool paid)
virtual ~Object ()
virtual void Update (double dt)
virtual void setPaid (bool p)
virtual bool getPaid ()
virtual float getValue ()
virtual string getIdentity ()
virtual Vector3 getStorePos (Player *player)
Data Fields
float hOrientation
float vOrientation
float apparentHealth
Inventory inventory
Camera3 camera
int jump
int speed
int holding
bool state [TOTAL_STATES]
bool inConversation
float value [TOTAL_VALUES]
Data Fields inherited from dynamicObject
Vector3 velocity
float hitDelay
float health
Data Fields inherited from Object
std::string type
Vector3 position
Collision collision
Mesh * mesh
float orientation
float size
bool ignoreCollision
Additional Inherited Members
Static Public Member Functions inherited from Object
static bool checkCollision (Object *a, Object *b)
Collsion checker function.
Detailed Description
This is the player class.
Class PLayer: dynamicObject
Definition at line 61 of file player.h.
Member Enumeration Documentation
enum Player::playerStates
Enumerator
JUMP
EATING
KNIFE
TOTAL_STATES
Definition at line 64 of file player.h.
enum Player::playerValues
Enumerator
bobbingX
bobbingY
knifeRotation
knifeStrike
knifeCooldown
eyeLevel
jumpCooldown
eatCooldown
eatElapsed
TOTAL_VALUES
Definition at line 72 of file player.h.
Constructor & Destructor Documentation
Player::Player () inline
Definition at line 85 of file player.h.
Player::~Player () inline
Definition at line 113 of file player.h.
Member Function Documentation
void Player::Control (double dt, vector< Object * > object) virtual
PLayer Control.
Definition at line 330 of file player.cpp.
References Inventory::canUse(), dynamicObject::hitDelay, hOrientation, inventory, Application::IsKeyPressed(), JUMP, jumpCooldown, Application::mouseButton(), speed, Vector3::SphericalToCartesian(), state, value, dynamicObject::velocity, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
float Player::getHealth () inline virtual
Reimplemented from dynamicObject.
Definition at line 134 of file player.h.
Referenced by PROJECTScene::Render(), and PROJECTScene::Update().
float Player::getRenderWallet () inline
Definition at line 132 of file player.h.
References Wallet::apparentValue, and Inventory::wallet.
Referenced by PROJECTScene::Render().
float Player::getWallet () inline
Definition at line 133 of file player.h.
References Wallet::trueValue, and Inventory::wallet.
bool Player::isEating () inline
Definition at line 136 of file player.h.
Referenced by PROJECTScene::Render().
void Player::Update (double dt, vector< Object * > object) virtual
PLayer Update function.
Definition at line 100 of file player.cpp.
References apparentHealth, bobbingX, bobbingY, bobXDir, bobYDir, camera, Inventory::canUse(), Control(), Inventory::Delete(), eatCooldown, eatElapsed, EATING, eyeLevel, Camera3::fov, Object::getHealth(), Inventory::getHolding(), dynamicObject::health, dynamicObject::hitDelay, hOrientation, inConversation, inventory, irrklang::ISoundEngine::isCurrentlyPlaying(), Application::IsKeyPressed(), jump, jumpCooldown, KNIFE, knifeCooldown, knifeDir, knifeRotation, knifeStrike, Vector3::Length(), Camera3::look, Application::mouseButton(), Camera3::Move(), Camera3::orientation, irrklang::ISoundEngine::play2D(), Camera::position, Object::position, dynamicObject::RespondToCollision(), speed, state, stopCamera, Object::type, Camera3::Update(), Inventory::Update(), dynamicObject::UpdateVelocity(), value, dynamicObject::velocity, vOrientation, Vector3::x, Vector3::y, and Vector3::z.
Referenced by PROJECTScene::Update().
Field Documentation
float Player::apparentHealth
Definition at line 117 of file player.h.
Referenced by Update().
Camera3 Player::camera
Definition at line 119 of file player.h.
Referenced by Doorway::ButtonUpdate(), dynamicObject::Control(), Storage::getStorePos(), MENUScene::Init(), PROJECTScene::Init(), PROJECTScene::Render(), PROJECTScene::RenderScene(), NPC::Update(), Update(), and PROJECTScene::Update().
int Player::holding
Definition at line 124 of file player.h.
Referenced by Doorway::ButtonUpdate(), dynamicObject::Control(), PROJECTScene::Render(), PROJECTScene::RenderScene(), dynamicObject::RespondToCollision(), and PROJECTScene::Update().
float Player::hOrientation
Definition at line 113 of file player.h.
Referenced by Control(), PROJECTScene::soundUpdate(), NPC::Update(), and Update().
bool Player::inConversation
Definition at line 126 of file player.h.
Referenced by Update(), and PROJECTScene::Update().
Inventory Player::inventory
Definition at line 118 of file player.h.
Referenced by Control(), S_Guard::Control(), Hobo::getConversation(), Cashier::getConversation(), PROJECTScene::Render(), Update(), and PROJECTScene::Update().
int Player::jump
Definition at line 121 of file player.h.
Referenced by PROJECTScene::Render(), and Update().
int Player::speed
Definition at line 122 of file player.h.
Referenced by Control(), PROJECTScene::Render(), and Update().
bool Player::state[TOTAL_STATES]
Definition at line 125 of file player.h.
Referenced by Control(), dynamicObject::RespondToCollision(), and Update().
float Player::value[TOTAL_VALUES]
Definition at line 127 of file player.h.
Referenced by Control(), PROJECTScene::Render(), and Update().
float Player::vOrientation
Definition at line 116 of file player.h.
Referenced by PROJECTScene::soundUpdate(), and Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/player.h
MyGraphics/Source/player.cpp