My Application: Manager Class Reference
Manager Class Reference
#include <NPC.h>
Public Member Functions
Manager ()
Manager (Vector3 p)
~Manager ()
virtual bool getCriteria (vector< Object * >object)
virtual void Init ()
virtual void Control (double dt, vector< Object * >object, Player *player)
Public Member Functions inherited from NPC
NPC (void)
~NPC (void)
string getIdentity ()
virtual TextBox * getConversation (Player *player)
void InitClues (const char *filename)
void InitDialogue (const char *filename)
virtual void InitQuest (const char *filename)
void Update (double dt, vector< Object * >object, Player *player)
void Orientate (float o, double dt, float speed)
void Orientate (Vector3 t, double dt, float speed)
void Goto (Vector3 destination, double dt, float turn, float speed)
void Animate (double dt, float speed)
void Animate (double dt, float speed, float limit)
Public Member Functions inherited from dynamicObject
dynamicObject ()
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m, Mesh *b)
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m, Mesh *b, float o)
~dynamicObject ()
void UpdateVelocity (double dt)
bool Knockback (Vector3 dir, Vector3 vel)
void RespondToCollision (Vector3 initialPos, vector< Object * >object)
void RespondToCollision (Vector3 initialPos, vector< Object * >object, Player *player)
float getHealth ()
Public Member Functions inherited from Object
Object ()
Object (Vector3 p, Vector3 c, Vector3 h)
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *b)
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, Mesh *b)
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, Mesh *b, float s, float o, bool i)
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, Mesh *b, float s, float o, bool i, bool paid)
~Object ()
virtual void Update (double dt)
virtual void setPaid (bool p)
virtual bool getPaid ()
virtual float getValue ()
virtual Vector3 getStorePos (Player *player)
Data Fields
ManagerQuest collection
Data Fields inherited from NPC
Vector3 initialPos
Vector3 previousPos
Vector3 target
Bodypart bodyParts [NUM_BODYPARTS]
string identity
float rotation [NUM_BODYPARTS]
int rotationDir [NUM_BODYPARTS]
float elapsedTime
vector< TextBox > greetings
vector< TextBox > clues
Quest * quest
bool inConversation
Data Fields inherited from dynamicObject
Vector3 velocity
float hitDelay
float health
Data Fields inherited from Object
std::string type
Vector3 position
Collision collision
Mesh * mesh
float orientation
float size
bool ignoreCollision
Additional Inherited Members
Public Types inherited from NPC
enum BodyParts {
HEAD, BODY, L_ARM, R_ARM,
L_LEG, R_LEG, NUM_BODYPARTS
}
Static Public Member Functions inherited from Object
static bool checkCollision (Object *a, Object *b)
Detailed Description
Definition at line 317 of file NPC.h.
Constructor & Destructor Documentation
Manager::Manager () inline
Definition at line 320 of file NPC.h.
References NPC::HEAD, Init(), Object::orientation, Object::position, NPC::rotation, and NPC::target.
Manager::Manager (Vector3 p) inline
Definition at line 328 of file NPC.h.
References Init(), Object::position, and NPC::target.
Manager::~Manager () inline
Definition at line 335 of file NPC.h.
Member Function Documentation
void Manager::Control (double dt, vector< Object * > object, Player * player) virtual
Reimplemented from NPC.
Definition at line 536 of file NPC.cpp.
References NPC::Orientate(), Object::position, NPC::target, and dynamicObject::velocity.
virtual bool Manager::getCriteria (vector< Object * > object) inline virtual
Reimplemented from NPC.
Definition at line 339 of file NPC.h.
References Quest::Accept, ManagerQuest::Criteria(), NPC::quest, and Button2D::trigger.
void Manager::Init () virtual
Reimplemented from NPC.
Definition at line 520 of file NPC.cpp.
References NPC::bodyParts, NPC::identity, Bodypart::identity, NPC::InitDialogue(), NPC::InitQuest(), LoadTGA(), Object::mesh, NPC::NUM_BODYPARTS, Object::position, and Mesh::textureID.
Referenced by Manager().
Field Documentation
ManagerQuest Manager::collection
Definition at line 335 of file NPC.h.
The documentation for this class was generated from the following files:
MyGraphics/Source/NPC.h
MyGraphics/Source/NPC.cpp