My Application: Blindman Class Reference
Blindman Class Reference
This the Blindman.
#include <NPC.h>
Public Member Functions
Blindman ()
Blindman (Vector3 p)
~Blindman ()
virtual void Init ()
Blindman Initializer.
virtual void Control (double dt, vector< Object * >object, Player *player)
Blindman Control.
Public Member Functions inherited from NPC
NPC (void)
virtual ~NPC (void)
string getIdentity ()
virtual bool getCriteria ()
virtual TextBox * getConversation (Player *player)
void InitDialogue (const char *filename)
Initialzier for the dialouge.
virtual void InitQuest (const char *filename)
Initialzier for hobo the quest text.
void Update (double dt, vector< Object * >object, Player *player)
Update function.
void Orientate (float o, double dt, float speed)
Orientation.
void Orientate (Vector3 t, double dt, float speed)
Overloaded orientation.
void Goto (Vector3 destination, double dt, float turn, float speed)
Go to function.
void Animate (double dt, float speed)
Animation.
void Animate (double dt, float speed, float limit)
Overloaded animate.
Public Member Functions inherited from dynamicObject
dynamicObject ()
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
dynamicObject (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float o)
~dynamicObject ()
void UpdateVelocity (double dt)
bool Knockback (Vector3 dir, Vector3 vel)
void RespondToCollision (Vector3 initialPos, vector< Object * >object)
void RespondToCollision (Vector3 initialPos, vector< Object * >object, Player *player)
dynamicObj RespondToCollision
float getHealth ()
Public Member Functions inherited from Object
Object ()
Object (Vector3 p, Vector3 c, Vector3 h)
Basic constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i)
Overloaded constructor.
Object (Vector3 p, Vector3 c, Vector3 h, Mesh *m, float s, float o, bool i, bool paid)
virtual ~Object ()
virtual void Update (double dt)
virtual void setPaid (bool p)
virtual bool getPaid ()
virtual float getValue ()
virtual Vector3 getStorePos (Player *player)
Additional Inherited Members
Public Types inherited from NPC
enum BodyParts {
HEAD, BODY, L_ARM, R_ARM,
L_LEG, R_LEG, NUM_BODYPARTS
}
Static Public Member Functions inherited from Object
static bool checkCollision (Object *a, Object *b)
Collsion checker function.
Data Fields inherited from NPC
Vector3 initialPos
Vector3 previousPos
Vector3 target
Bodypart bodyParts [NUM_BODYPARTS]
string identity
float rotation [NUM_BODYPARTS]
int rotationDir [NUM_BODYPARTS]
float elapsedTime
vector< TextBox > greetings
vector< TextBox > clues
Quest * quest
bool inConversation
Data Fields inherited from dynamicObject
Vector3 velocity
float hitDelay
float health
Data Fields inherited from Object
std::string type
Vector3 position
Collision collision
Mesh * mesh
float orientation
float size
bool ignoreCollision
Detailed Description
This the Blindman.
Class Blindman: NPC
Definition at line 224 of file NPC.h.
Constructor & Destructor Documentation
Blindman::Blindman () inline
Definition at line 227 of file NPC.h.
References Init(), Object::orientation, Object::position, Vector3::SphericalToCartesian(), NPC::target, and Vector3::y.
Blindman::Blindman (Vector3 p) inline
Definition at line 237 of file NPC.h.
References Init(), Object::orientation, Object::position, Vector3::SphericalToCartesian(), NPC::target, and Vector3::y.
Blindman::~Blindman () inline
Definition at line 246 of file NPC.h.
Member Function Documentation
void Blindman::Control (double dt, vector< Object * > object, Player * player) virtual
Blindman Control.
NPC:
Reimplemented from NPC.
Definition at line 463 of file NPC.cpp.
References NPC::Animate(), Collision::centre, Object::checkCollision(), Object::collision, NPC::elapsedTime, dynamicObject::getHealth(), NPC::Goto(), Collision::hitbox, dynamicObject::hitDelay, Object::ignoreCollision, NPC::initialPos, dynamicObject::Knockback(), Object::orientation, Object::position, Vector3::SphericalToCartesian(), NPC::target, Object::type, dynamicObject::velocity, Vector3::x, Vector3::y, and Vector3::z.
void Blindman::Init () virtual
Blindman Initializer.
NPC:
Reimplemented from NPC.
Definition at line 443 of file NPC.cpp.
References NPC::bodyParts, NPC::identity, Bodypart::identity, NPC::InitDialogue(), LoadTGA(), Object::mesh, NPC::NUM_BODYPARTS, Object::position, and Mesh::textureID.
Referenced by Blindman().
The documentation for this class was generated from the following files:
MyGraphics/Source/NPC.h
MyGraphics/Source/NPC.cpp