My Application: Inventory Class Reference
Inventory Class Reference
#include <inventory.h>
Public Member Functions
Inventory ()
~Inventory ()
int emptySlot ()
bool checkPaid ()
bool canUse ()
bool Insert (Object *o)
float checkPrice ()
bool Checkout ()
bool Remove ()
bool Delete ()
void Init (Vector3 pos)
void Update (double dt)
Object * getHolding ()
Data Fields
Wallet wallet
Vector3 position
Slot slots [9]
Selector selector
int index
Mesh * slotMeshes [3]
Detailed Description
Definition at line 82 of file inventory.h.
Constructor & Destructor Documentation
Inventory::Inventory () inline
Definition at line 85 of file inventory.h.
Inventory::~Inventory () inline
Definition at line 86 of file inventory.h.
Member Function Documentation
bool Inventory::canUse ()
Definition at line 193 of file inventory.cpp.
References Slot::item, Selector::selectedSlot, and selector.
Referenced by Player::Control(), and Player::Update().
bool Inventory::Checkout ()
Definition at line 107 of file inventory.cpp.
References checkPrice(), Slot::item, slots, Wallet::trueValue, and wallet.
Referenced by PROJECTScene::Update().
bool Inventory::checkPaid ()
Definition at line 204 of file inventory.cpp.
References slots.
Referenced by S_Guard::Control(), and Cashier::getConversation().
float Inventory::checkPrice ()
Definition at line 86 of file inventory.cpp.
References Slot::item, and slots.
Referenced by Checkout(), Checkout::GenerateText(), and PROJECTScene::Update().
bool Inventory::Delete ()
Definition at line 170 of file inventory.cpp.
References Slot::item, Selector::selectedSlot, and selector.
Referenced by Player::Update(), and PROJECTScene::Update().
int Inventory::emptySlot ()
Definition at line 218 of file inventory.cpp.
References slots.
Referenced by Insert().
Object* Inventory::getHolding () inline
Definition at line 109 of file inventory.h.
References Slot::item, and Selector::selectedSlot.
Referenced by Donation::GenerateText(), Hobo::getConversation(), PROJECTScene::Render(), Player::Update(), and PROJECTScene::Update().
void Inventory::Init (Vector3 pos)
Definition at line 3 of file inventory.cpp.
References MeshBuilder::GenerateXYQuad(), index, LoadTGA(), Slot::mesh, Selector::mesh, Slot::position, position, Selector::selectedSlot, selector, slotMeshes, slots, Mesh::textureID, and Vector3::x.
bool Inventory::Insert (Object * o)
Definition at line 149 of file inventory.cpp.
References emptySlot(), Object::getPaid(), Slot::item, Object::mesh, Mesh::name, and slots.
Referenced by PROJECTScene::Update().
bool Inventory::Remove ()
Definition at line 182 of file inventory.cpp.
References Slot::item, Selector::selectedSlot, and selector.
Referenced by PROJECTScene::Update().
void Inventory::Update (double dt)
Definition at line 29 of file inventory.cpp.
References index, Application::IsKeyPressed(), Slot::mesh, Application::mouseScroll, Selector::selectedSlot, selector, slotMeshes, slots, Wallet::Update(), and wallet.
Referenced by Player::Update().
Field Documentation
int Inventory::index
Definition at line 92 of file inventory.h.
Referenced by Init(), and Update().
Vector3 Inventory::position
Definition at line 89 of file inventory.h.
Referenced by Init().
Selector Inventory::selector
Definition at line 91 of file inventory.h.
Referenced by canUse(), Delete(), Init(), Remove(), PROJECTScene::Render(), Update(), and PROJECTScene::Update().
Mesh* Inventory::slotMeshes[3]
Definition at line 94 of file inventory.h.
Referenced by Init(), and Update().
Slot Inventory::slots[9]
Definition at line 90 of file inventory.h.
Referenced by Checkout(), checkPaid(), checkPrice(), emptySlot(), Init(), Insert(), PROJECTScene::Render(), and Update().
Wallet Inventory::wallet
Definition at line 86 of file inventory.h.
Referenced by Checkout(), Player::getRenderWallet(), Player::getWallet(), Update(), and PROJECTScene::Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/inventory.h
MyGraphics/Source/inventory.cpp