My Application: Application Class Reference
Application Class Reference
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
void Run ()
void Exit ()
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
static bool mouseButton (unsigned short button)
static Position getMousePos ()
Static Public Attributes
static int mouseScroll = 0
Private Attributes
StopWatch m_timer
Detailed Description
Definition at line 8 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 56 of file Application.cpp.
Application::~Application ()
Definition at line 60 of file Application.cpp.
Member Function Documentation
void Application::Exit ()
Definition at line 189 of file Application.cpp.
References m_window.
Referenced by main().
Position Application::getMousePos () static
Definition at line 116 of file Application.cpp.
References m_window.
Referenced by Camera3::Move(), and Run().
void Application::Init ()
Definition at line 64 of file Application.cpp.
References error_callback(), m_window, and resize_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Definition at line 46 of file Application.cpp.
Referenced by Doorway::ButtonUpdate(), dynamicObject::Control(), Player::Control(), MENUScene::RenderScene(), PROJECTScene::RenderScene(), Run(), Camera::Update(), MENUScene::Update(), Inventory::Update(), Player::Update(), and PROJECTScene::Update().
bool Application::mouseButton (unsigned short button) static
Definition at line 51 of file Application.cpp.
References m_window.
Referenced by Player::Control(), NPC::Update(), Player::Update(), and PROJECTScene::Update().
void Application::Run ()
Definition at line 130 of file Application.cpp.
References Scene::Exit(), frameTime, StopWatch::getElapsedTime(), getMousePos(), Scene::Init(), IsKeyPressed(), lastCursor, m_timer, m_window, Scene::pause, pauseDelay, play, quit, Scene::Render(), scroll_callback(), StopWatch::startTimer(), Scene::Update(), StopWatch::waitUntil(), Position::x, and Position::y.
Referenced by main().
Field Documentation
StopWatch Application::m_timer private
Definition at line 24 of file Application.h.
Referenced by Run().
int Application::mouseScroll = 0 static
Definition at line 18 of file Application.h.
Referenced by scroll_callback(), MENUScene::Update(), Inventory::Update(), PROJECTScene::Update(), and Camera3::Zoom().
The documentation for this class was generated from the following files:
MyGraphics/Source/Application.h
MyGraphics/Source/Application.cpp