My Application: MyGraphics/Source/LoadTGA.cpp File Reference
LoadTGA.cpp File Reference
#include <iostream>
#include <fstream>
#include "LoadTGA.h"
Functions
GLuint LoadTGA (const char *file_path)
Function Documentation
GLuint LoadTGA (const char * file_path)
Definition at line 8 of file LoadTGA.cpp.
Referenced by PROJECTScene::DarrenInit(), Vending::generateDrink(), MENUScene::Init(), Hobo::Init(), Inventory::Init(), PROJECTScene::Init(), Doorway::Init(), Thug::Init(), Cashier::Init(), Blindman::Init(), Detective::Init(), S_Guard::Init(), Manager::Init(), MENUScene::InitJunk(), PROJECTScene::InitJunk(), PROJECTScene::JeremiahInit(), PROJECTScene::JessicaInit(), and PROJECTScene::RicssonInit().