My Application: MyGraphics/Source/MeshBuilder.cpp File Reference
MeshBuilder.cpp File Reference
To generate meshes of different shapes.
#include "vertex.h"
#include "MeshBuilder.h"
#include "MyMath.h"
#include <GL\glew.h>
#include <vector>
Macros
#define PI 3.14159265
Functions
float sphereX (float phi, float theta)
float sphereY (float phi)
float sphereZ (float phi, float theta)
float cylinderX (float theta)
float cylinderZ (float theta)
Detailed Description
To generate meshes of different shapes.
Author
Ricsson Toh
Definition in file MeshBuilder.cpp.
Macro Definition Documentation
#define PI 3.14159265
Definition at line 16 of file MeshBuilder.cpp.
Referenced by MeshBuilder::GenerateCircle(), and MeshBuilder::GenerateRing().
Function Documentation
float cylinderX (float theta)
Definition at line 584 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float cylinderZ (float theta)
Definition at line 589 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float sphereX (float phi, float theta)
Definition at line 569 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCapsule(), MeshBuilder::GenerateHemi(), and MeshBuilder::GenerateSphere().
float sphereY (float phi)
Definition at line 574 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCapsule(), MeshBuilder::GenerateCone(), MeshBuilder::GenerateHemi(), and MeshBuilder::GenerateSphere().
float sphereZ (float phi, float theta)
Definition at line 579 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCapsule(), MeshBuilder::GenerateHemi(), and MeshBuilder::GenerateSphere().